language: minimal

sudo: false

matrix:
  fast_finish: true
  include:
    - name: "default"
      env: TEST_TARGET=default PY=3.7
    - name: "coding_standards"
      env: TEST_TARGET=coding_standards PY=3.7
    - name: "docs"
      env: TEST_TARGET=docs PY=3.7

before_install:
  - wget http://bit.ly/miniconda -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda update conda
  - conda config --add channels conda-forge --force
  - conda config --remove channels defaults
  - conda create --name TEST python=$PY --file requirements.txt --file requirements-dev.txt
  - source activate TEST

install:
  - python setup.py sdist && version=$(python setup.py --version) && pushd dist && pip install nbrr-${version}.tar.gz && popd

script:
  - if [[ $TEST_TARGET == 'default' ]]; then
      cp -r tests/ /tmp ;
      pushd /tmp && pytest -n 2 -rxs tests && popd ;
    fi

  - if [[ $TEST_TARGET == 'coding_standards' ]]; then
      flake8 --max-line-length=105 nbrr --exclude=_version.py ;
      flake8 --max-line-length=105 tests ;
    fi

deploy:
  skip_cleanup: true
  provider: pypi
  user: ocefpaf
  password:
    secure: HD3oiZ3aWzGlmMpoZqsu8uG6v7Zhk/VgqrU+Ch0y0MQFCl8Dagh8Wuo6iLKGWimqSQ3vl3CpXZAhCZRyv/iEZLVf3f5rDiPpQNgvAARZANxMolidGEa+HBhzNOPtJQ78d76ikJ9fe575cO5FEzJi+7NgHFXucyjr+1kINDjPXNvhLeUEaT+C7+uOYrCc0hkznDs0sCwsNGIYvy+cyjQL2FsLmoqRzwsliCTSXNBLJ3fw15BlXGRbHCXT1qf+8kNAGdR650a3c+jazz76ElIdjsg7E//bWmxiePHgBuctnIXNTdMxEi2rMC2QqURV/UEdZMb361bAk3avu1/vuTrOiO86As1hzh+luQVF/jK0x90mpPSlCYN2cyvx2eliLgrDNSzmIiL1H5YYlXSqLX80hb2+YQE8hNwe53SGAhYBO1bktyAuIno4+vK54wShnpqK/alcwvpB3uwx3QNCUKcKEQwzTs6bJVSYWySCyy7fuIGFX+mwdzOOyLrhnWIIimyolpITzbfOqCf/5FnGXoIZ7Kjm4CTGqqaEos4wG2CXDsz8dlgU8xSz1nImZlg6mM+6h/hLxaUtRsw79ZLZZ8/IsKUewWTi/FPJPB8Dri8+3Qa74JppNWVkb7DxNYYErxOGRF6GHGRtsBb4I2stupD2VNGKHFZO1Cg+G9RyUOHAlT4=
  distributions: sdist bdist_wheel
  upload_docs: no
  on:
    repo: pyoceans/erddapy
    tags: true
    all_branches: master
    condition: '$TEST_TARGET == "default"'
